# Generated by Django 2.0.3 on 2019-12-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=64)),
                ('productID', models.CharField(max_length=64)),
                ('topings', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('logeado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('rank', models.IntegerField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=64)),
                ('productID', models.CharField(max_length=64)),
                ('topings', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=64)),
                ('tipe', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(default='', max_length=64)),
                ('tipo', models.CharField(max_length=64)),
            ],
        ),
    ]
